/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

(* cells_not_processed =  1  *)
(* src = "Automatic-Parking-Access-Control.v:13.1-142.10" *)
module ControladorParqueo(clk, rst, sensor_1, sensor_2, try_psswrd, psswrd_atmpt, alarm_1, alarm_2, open_gate, close_gate);
  (* src = "APAC_synth.v:22.8-22.13" *)
  wire _008_;
  (* src = "APAC_synth.v:23.8-23.13" *)
  wire _009_;
  (* src = "APAC_synth.v:24.8-24.13" *)
  wire _010_;
  (* src = "APAC_synth.v:25.8-25.13" *)
  wire _011_;
  (* src = "APAC_synth.v:26.8-26.13" *)
  wire _012_;
  (* src = "APAC_synth.v:27.8-27.13" *)
  wire _013_;
  (* src = "APAC_synth.v:28.8-28.13" *)
  wire _014_;
  (* src = "APAC_synth.v:29.8-29.13" *)
  wire _015_;
  (* src = "APAC_synth.v:30.8-30.13" *)
  wire _016_;
  (* src = "APAC_synth.v:31.8-31.13" *)
  wire _017_;
  (* src = "APAC_synth.v:32.8-32.13" *)
  wire _018_;
  (* src = "APAC_synth.v:33.8-33.13" *)
  wire _019_;
  (* src = "Automatic-Parking-Access-Control.v:35.11-35.17" *)
  wire _020_;
  (* src = "Automatic-Parking-Access-Control.v:35.11-35.17" *)
  wire _021_;
  (* src = "Automatic-Parking-Access-Control.v:35.11-35.17" *)
  wire _022_;
  (* src = "Automatic-Parking-Access-Control.v:35.11-35.17" *)
  wire _023_;
  (* src = "Automatic-Parking-Access-Control.v:35.11-35.17" *)
  wire _024_;
  (* src = "APAC_synth.v:44.8-44.13" *)
  wire _025_;
  (* src = "APAC_synth.v:45.8-45.13" *)
  wire _026_;
  (* src = "APAC_synth.v:46.8-46.13" *)
  wire _027_;
  (* src = "APAC_synth.v:47.8-47.13" *)
  wire _028_;
  (* src = "APAC_synth.v:48.8-48.13" *)
  wire _029_;
  (* src = "APAC_synth.v:49.8-49.13" *)
  wire _030_;
  (* src = "APAC_synth.v:50.8-50.13" *)
  wire _031_;
  (* src = "APAC_synth.v:51.8-51.13" *)
  wire _032_;
  (* src = "APAC_synth.v:52.8-52.13" *)
  wire _033_;
  (* src = "APAC_synth.v:53.8-53.13" *)
  wire _034_;
  (* src = "APAC_synth.v:54.8-54.13" *)
  wire _035_;
  (* src = "APAC_synth.v:55.8-55.13" *)
  wire _036_;
  (* src = "APAC_synth.v:56.8-56.13" *)
  wire _037_;
  (* src = "APAC_synth.v:57.8-57.13" *)
  wire _038_;
  (* src = "APAC_synth.v:58.8-58.13" *)
  wire _039_;
  (* src = "APAC_synth.v:59.8-59.13" *)
  wire _040_;
  (* src = "APAC_synth.v:60.8-60.13" *)
  wire _041_;
  (* src = "APAC_synth.v:61.8-61.13" *)
  wire _042_;
  (* src = "APAC_synth.v:62.8-62.13" *)
  wire _043_;
  (* src = "APAC_synth.v:63.8-63.13" *)
  wire _044_;
  (* src = "APAC_synth.v:64.8-64.13" *)
  wire _045_;
  (* src = "APAC_synth.v:65.8-65.13" *)
  wire _046_;
  (* src = "APAC_synth.v:66.8-66.13" *)
  wire _047_;
  (* src = "APAC_synth.v:67.8-67.13" *)
  wire _048_;
  (* src = "APAC_synth.v:68.8-68.13" *)
  wire _049_;
  (* src = "APAC_synth.v:69.8-69.13" *)
  wire _050_;
  (* src = "APAC_synth.v:70.8-70.13" *)
  wire _051_;
  (* src = "APAC_synth.v:71.8-71.13" *)
  wire _052_;
  (* src = "APAC_synth.v:72.8-72.13" *)
  wire _053_;
  (* src = "APAC_synth.v:73.8-73.13" *)
  wire _054_;
  (* src = "APAC_synth.v:74.8-74.13" *)
  wire _055_;
  (* src = "APAC_synth.v:75.8-75.13" *)
  wire _056_;
  (* src = "APAC_synth.v:76.8-76.13" *)
  wire _057_;
  (* src = "APAC_synth.v:77.8-77.13" *)
  wire _058_;
  (* src = "APAC_synth.v:78.8-78.13" *)
  wire _059_;
  (* src = "APAC_synth.v:79.8-79.13" *)
  wire _060_;
  (* src = "APAC_synth.v:80.8-80.13" *)
  wire _061_;
  (* src = "APAC_synth.v:81.8-81.13" *)
  wire _062_;
  (* src = "APAC_synth.v:82.8-82.13" *)
  wire _063_;
  (* src = "APAC_synth.v:83.8-83.13" *)
  wire _064_;
  (* src = "APAC_synth.v:84.8-84.13" *)
  wire _065_;
  (* src = "APAC_synth.v:85.8-85.13" *)
  wire _066_;
  (* src = "APAC_synth.v:86.8-86.13" *)
  wire _067_;
  (* src = "APAC_synth.v:87.8-87.13" *)
  wire _068_;
  (* src = "APAC_synth.v:88.8-88.13" *)
  wire _069_;
  (* src = "APAC_synth.v:89.8-89.13" *)
  wire _070_;
  (* src = "APAC_synth.v:90.8-90.13" *)
  wire _071_;
  (* src = "APAC_synth.v:91.8-91.13" *)
  wire _072_;
  (* src = "APAC_synth.v:92.8-92.13" *)
  wire _073_;
  (* src = "APAC_synth.v:93.8-93.13" *)
  wire _074_;
  (* src = "APAC_synth.v:94.8-94.13" *)
  wire _075_;
  (* src = "APAC_synth.v:95.8-95.13" *)
  wire _076_;
  (* src = "APAC_synth.v:96.8-96.13" *)
  wire _077_;
  (* src = "APAC_synth.v:97.8-97.13" *)
  wire _078_;
  (* src = "APAC_synth.v:98.8-98.13" *)
  wire _079_;
  (* src = "APAC_synth.v:99.8-99.13" *)
  wire _080_;
  (* src = "APAC_synth.v:100.8-100.13" *)
  wire _081_;
  (* src = "APAC_synth.v:101.8-101.13" *)
  wire _082_;
  (* src = "APAC_synth.v:102.8-102.13" *)
  wire _083_;
  (* src = "APAC_synth.v:103.8-103.13" *)
  wire _084_;
  (* src = "APAC_synth.v:104.8-104.13" *)
  wire _085_;
  (* src = "APAC_synth.v:105.8-105.13" *)
  wire _086_;
  (* src = "APAC_synth.v:106.8-106.13" *)
  wire _087_;
  (* src = "APAC_synth.v:107.8-107.13" *)
  wire _088_;
  (* src = "APAC_synth.v:108.8-108.13" *)
  wire _089_;
  (* src = "APAC_synth.v:109.8-109.13" *)
  wire _090_;
  (* src = "APAC_synth.v:110.8-110.13" *)
  wire _091_;
  (* src = "APAC_synth.v:111.8-111.13" *)
  wire _092_;
  (* src = "APAC_synth.v:112.8-112.13" *)
  wire _093_;
  (* src = "APAC_synth.v:113.8-113.13" *)
  wire _094_;
  (* src = "APAC_synth.v:114.8-114.13" *)
  wire _095_;
  (* src = "APAC_synth.v:115.8-115.13" *)
  wire _096_;
  (* src = "APAC_synth.v:116.8-116.13" *)
  wire _097_;
  (* src = "APAC_synth.v:117.8-117.13" *)
  wire _098_;
  (* src = "APAC_synth.v:118.8-118.13" *)
  wire _099_;
  (* src = "APAC_synth.v:119.8-119.13" *)
  wire _100_;
  (* src = "APAC_synth.v:120.8-120.13" *)
  wire _101_;
  (* src = "APAC_synth.v:121.8-121.13" *)
  wire _102_;
  (* src = "APAC_synth.v:122.8-122.13" *)
  wire _103_;
  (* src = "APAC_synth.v:123.8-123.13" *)
  wire _104_;
  (* src = "APAC_synth.v:124.8-124.13" *)
  wire _105_;
  (* src = "APAC_synth.v:125.8-125.13" *)
  wire _106_;
  (* src = "APAC_synth.v:126.8-126.13" *)
  wire _107_;
  (* src = "APAC_synth.v:127.8-127.13" *)
  wire _108_;
  (* src = "APAC_synth.v:128.8-128.13" *)
  wire _109_;
  (* src = "APAC_synth.v:129.8-129.13" *)
  wire _110_;
  (* src = "APAC_synth.v:130.8-130.13" *)
  wire _111_;
  (* src = "APAC_synth.v:131.8-131.13" *)
  wire _112_;
  (* src = "APAC_synth.v:132.8-132.13" *)
  wire _113_;
  (* src = "APAC_synth.v:133.8-133.13" *)
  wire _114_;
  (* src = "APAC_synth.v:134.8-134.13" *)
  wire _115_;
  (* src = "APAC_synth.v:135.8-135.13" *)
  wire _116_;
  (* src = "APAC_synth.v:136.8-136.13" *)
  wire _117_;
  (* src = "APAC_synth.v:137.8-137.13" *)
  wire _118_;
  (* src = "APAC_synth.v:138.8-138.13" *)
  wire _119_;
  (* src = "APAC_synth.v:139.8-139.13" *)
  wire _120_;
  (* src = "APAC_synth.v:140.8-140.13" *)
  wire _121_;
  (* src = "APAC_synth.v:141.8-141.13" *)
  wire _122_;
  (* src = "APAC_synth.v:142.8-142.13" *)
  wire _123_;
  (* src = "APAC_synth.v:143.8-143.13" *)
  wire _124_;
  (* src = "APAC_synth.v:144.8-144.13" *)
  wire _125_;
  (* src = "APAC_synth.v:145.8-145.13" *)
  wire _126_;
  (* src = "APAC_synth.v:146.8-146.13" *)
  wire _127_;
  (* src = "APAC_synth.v:147.8-147.13" *)
  wire _128_;
  (* src = "APAC_synth.v:148.8-148.13" *)
  wire _129_;
  (* src = "APAC_synth.v:149.8-149.13" *)
  wire _130_;
  (* src = "APAC_synth.v:150.8-150.13" *)
  wire _131_;
  (* src = "APAC_synth.v:151.8-151.13" *)
  wire _132_;
  (* src = "APAC_synth.v:152.8-152.13" *)
  wire _133_;
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:62.5-137.12|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire _134_;
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:62.5-137.12|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire _135_;
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:62.5-137.12|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _136_;
  (* src = "Automatic-Parking-Access-Control.v:34.11-34.16" *)
  wire _148_;
  (* src = "Automatic-Parking-Access-Control.v:34.11-34.16" *)
  wire _149_;
  (* src = "Automatic-Parking-Access-Control.v:34.11-34.16" *)
  wire _150_;
  (* src = "Automatic-Parking-Access-Control.v:31.12-31.19" *)
  output alarm_1;
  reg alarm_1;
  (* src = "Automatic-Parking-Access-Control.v:31.21-31.28" *)
  output alarm_2;
  reg alarm_2;
  (* src = "Automatic-Parking-Access-Control.v:27.7-27.10" *)
  input clk;
  wire clk;
  (* src = "Automatic-Parking-Access-Control.v:31.41-31.51" *)
  output close_gate;
  reg close_gate;
  (* src = "Automatic-Parking-Access-Control.v:35.11-35.17" *)
  wire [4:0] count0;
  (* src = "Automatic-Parking-Access-Control.v:37.11-37.20" *)
  (* unused_bits = "0 1 2 3 4" *)
  wire [4:0] nxt_state;
  (* src = "Automatic-Parking-Access-Control.v:31.30-31.39" *)
  output open_gate;
  reg open_gate;
  (* src = "Automatic-Parking-Access-Control.v:28.13-28.25" *)
  input [7:0] psswrd_atmpt;
  wire [7:0] psswrd_atmpt;
  (* src = "Automatic-Parking-Access-Control.v:27.12-27.15" *)
  input rst;
  wire rst;
  (* src = "Automatic-Parking-Access-Control.v:27.17-27.25" *)
  input sensor_1;
  wire sensor_1;
  (* src = "Automatic-Parking-Access-Control.v:27.27-27.35" *)
  input sensor_2;
  wire sensor_2;
  (* src = "Automatic-Parking-Access-Control.v:34.11-34.16" *)
  wire [4:0] state;
  (* src = "Automatic-Parking-Access-Control.v:27.37-27.47" *)
  input try_psswrd;
  wire try_psswrd;
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  always @*
    if (!_011_) close_gate = _134_;
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  always @*
    if (!_008_) alarm_1 = _135_;
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  always @*
    if (!_009_) alarm_2 = _136_;
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  always @*
    if (!_010_) open_gate = _135_;
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:371.7-374.4" *)
  NOT _275_ (
    .A(_148_),
    .Y(_073_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:375.7-378.4" *)
  NOT _276_ (
    .A(_149_),
    .Y(_074_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:379.7-382.4" *)
  NOT _277_ (
    .A(_150_),
    .Y(_075_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:383.7-386.4" *)
  NOT _278_ (
    .A(_021_),
    .Y(_076_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:387.7-390.4" *)
  NOT _279_ (
    .A(_022_),
    .Y(_077_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:391.7-394.4" *)
  NOT _280_ (
    .A(_023_),
    .Y(_078_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:395.7-398.4" *)
  NOT _281_ (
    .A(_024_),
    .Y(_079_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:399.7-402.4" *)
  NOT _282_ (
    .A(rst),
    .Y(_080_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:403.7-406.4" *)
  NOT _283_ (
    .A(try_psswrd),
    .Y(_081_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:407.7-410.4" *)
  NOT _284_ (
    .A(psswrd_atmpt[6]),
    .Y(_082_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:411.7-414.4" *)
  NOT _285_ (
    .A(sensor_1),
    .Y(_083_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:415.8-419.4" *)
  NAND _286_ (
    .A(_149_),
    .B(_075_),
    .Y(_084_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:420.7-423.4" *)
  NOT _287_ (
    .A(_084_),
    .Y(_085_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:424.8-428.4" *)
  NAND _288_ (
    .A(_148_),
    .B(_075_),
    .Y(_086_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:429.8-433.4" *)
  NAND _289_ (
    .A(_148_),
    .B(_085_),
    .Y(_087_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:434.7-437.4" *)
  NOT _290_ (
    .A(_087_),
    .Y(_088_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:438.8-442.4" *)
  NAND _291_ (
    .A(_020_),
    .B(_021_),
    .Y(_089_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:443.7-447.4" *)
  NOR _292_ (
    .A(_022_),
    .B(_089_),
    .Y(_090_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:448.7-452.4" *)
  NOR _293_ (
    .A(_023_),
    .B(_024_),
    .Y(_091_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:453.8-457.4" *)
  NAND _294_ (
    .A(_090_),
    .B(_091_),
    .Y(_092_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:458.7-461.4" *)
  NOT _295_ (
    .A(_092_),
    .Y(_093_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:462.7-466.4" *)
  NOR _296_ (
    .A(_149_),
    .B(_086_),
    .Y(_135_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:467.8-471.4" *)
  NAND _297_ (
    .A(sensor_1),
    .B(sensor_2),
    .Y(_094_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:472.7-475.4" *)
  NOT _298_ (
    .A(_094_),
    .Y(_095_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:476.8-480.4" *)
  NAND _299_ (
    .A(_135_),
    .B(_094_),
    .Y(_096_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:481.7-485.4" *)
  NOR _300_ (
    .A(_092_),
    .B(_096_),
    .Y(_097_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:486.7-490.4" *)
  NOR _301_ (
    .A(_088_),
    .B(_097_),
    .Y(_098_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:491.7-495.4" *)
  NOR _302_ (
    .A(try_psswrd),
    .B(_098_),
    .Y(_099_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:496.7-500.4" *)
  NOR _303_ (
    .A(_150_),
    .B(_099_),
    .Y(_100_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:501.7-505.4" *)
  NOR _304_ (
    .A(_073_),
    .B(_100_),
    .Y(_101_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:506.8-510.4" *)
  NAND _305_ (
    .A(psswrd_atmpt[2]),
    .B(psswrd_atmpt[1]),
    .Y(_102_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:511.8-515.4" *)
  NAND _306_ (
    .A(psswrd_atmpt[0]),
    .B(_082_),
    .Y(_103_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:516.7-520.4" *)
  NOR _307_ (
    .A(_102_),
    .B(_103_),
    .Y(_104_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:521.8-525.4" *)
  NAND _308_ (
    .A(psswrd_atmpt[7]),
    .B(psswrd_atmpt[5]),
    .Y(_105_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:526.8-530.4" *)
  NAND _309_ (
    .A(psswrd_atmpt[4]),
    .B(psswrd_atmpt[3]),
    .Y(_106_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:531.7-535.4" *)
  NOR _310_ (
    .A(_105_),
    .B(_106_),
    .Y(_107_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:536.8-540.4" *)
  NAND _311_ (
    .A(_104_),
    .B(_107_),
    .Y(_108_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:541.8-545.4" *)
  NAND _312_ (
    .A(psswrd_atmpt[5]),
    .B(_082_),
    .Y(_109_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:546.8-550.4" *)
  NAND _313_ (
    .A(psswrd_atmpt[3]),
    .B(psswrd_atmpt[1]),
    .Y(_110_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:551.7-555.4" *)
  NOR _314_ (
    .A(_109_),
    .B(_110_),
    .Y(_111_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:556.8-560.4" *)
  NAND _315_ (
    .A(psswrd_atmpt[4]),
    .B(psswrd_atmpt[2]),
    .Y(_112_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:561.8-565.4" *)
  NAND _316_ (
    .A(psswrd_atmpt[7]),
    .B(psswrd_atmpt[0]),
    .Y(_113_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:566.7-570.4" *)
  NOR _317_ (
    .A(_112_),
    .B(_113_),
    .Y(_114_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:571.8-575.4" *)
  NAND _318_ (
    .A(_111_),
    .B(_114_),
    .Y(_115_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:576.8-580.4" *)
  NAND _319_ (
    .A(try_psswrd),
    .B(_115_),
    .Y(_116_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:581.7-585.4" *)
  NOR _320_ (
    .A(try_psswrd),
    .B(_095_),
    .Y(_117_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:586.8-590.4" *)
  NAND _321_ (
    .A(_092_),
    .B(_117_),
    .Y(_118_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:591.8-595.4" *)
  NAND _322_ (
    .A(_116_),
    .B(_118_),
    .Y(_119_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:596.8-600.4" *)
  NAND _323_ (
    .A(_135_),
    .B(_119_),
    .Y(_120_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:601.7-605.4" *)
  NOR _324_ (
    .A(_087_),
    .B(_116_),
    .Y(_121_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:606.7-610.4" *)
  NOR _325_ (
    .A(_148_),
    .B(_150_),
    .Y(_122_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:611.7-615.4" *)
  NOR _326_ (
    .A(_148_),
    .B(_084_),
    .Y(_134_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:616.8-620.4" *)
  NAND _327_ (
    .A(_074_),
    .B(_122_),
    .Y(_123_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:621.7-625.4" *)
  NOR _328_ (
    .A(_149_),
    .B(_150_),
    .Y(_124_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:626.7-630.4" *)
  NOR _329_ (
    .A(_135_),
    .B(_122_),
    .Y(_125_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:631.7-635.4" *)
  NOR _330_ (
    .A(_083_),
    .B(_123_),
    .Y(_126_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:636.7-640.4" *)
  NOR _331_ (
    .A(_095_),
    .B(_126_),
    .Y(_127_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:641.7-645.4" *)
  NOR _332_ (
    .A(_125_),
    .B(_127_),
    .Y(_128_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:646.7-650.4" *)
  NOR _333_ (
    .A(_121_),
    .B(_128_),
    .Y(_129_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:651.8-655.4" *)
  NAND _334_ (
    .A(_120_),
    .B(_129_),
    .Y(_130_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:656.7-660.4" *)
  NOR _335_ (
    .A(_101_),
    .B(_130_),
    .Y(_131_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:661.7-665.4" *)
  NOR _336_ (
    .A(rst),
    .B(_131_),
    .Y(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:666.7-670.4" *)
  NOR _337_ (
    .A(_074_),
    .B(_100_),
    .Y(_132_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:671.8-675.4" *)
  NAND _338_ (
    .A(_095_),
    .B(_124_),
    .Y(_133_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:676.8-680.4" *)
  NAND _339_ (
    .A(_083_),
    .B(sensor_2),
    .Y(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:681.8-685.4" *)
  NAND _340_ (
    .A(_134_),
    .B(_025_),
    .Y(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:686.8-690.4" *)
  NAND _341_ (
    .A(_133_),
    .B(_026_),
    .Y(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:691.7-695.4" *)
  NOR _342_ (
    .A(_121_),
    .B(_027_),
    .Y(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:696.7-700.4" *)
  NOR _343_ (
    .A(_081_),
    .B(_108_),
    .Y(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:701.8-705.4" *)
  NAND _344_ (
    .A(_135_),
    .B(_029_),
    .Y(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:706.8-710.4" *)
  NAND _345_ (
    .A(_028_),
    .B(_030_),
    .Y(_031_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:711.7-715.4" *)
  NOR _346_ (
    .A(_081_),
    .B(_115_),
    .Y(_032_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:716.7-720.4" *)
  NOR _347_ (
    .A(_132_),
    .B(_031_),
    .Y(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:721.7-725.4" *)
  NOR _348_ (
    .A(rst),
    .B(_033_),
    .Y(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:726.7-730.4" *)
  NOR _349_ (
    .A(_075_),
    .B(rst),
    .Y(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:731.7-735.4" *)
  NOR _350_ (
    .A(_081_),
    .B(_096_),
    .Y(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:736.7-740.4" *)
  NOR _351_ (
    .A(_096_),
    .B(_116_),
    .Y(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:741.7-745.4" *)
  NOR _352_ (
    .A(_020_),
    .B(_035_),
    .Y(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:746.8-750.4" *)
  NAND _353_ (
    .A(_020_),
    .B(try_psswrd),
    .Y(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:751.7-755.4" *)
  NOR _354_ (
    .A(_096_),
    .B(_037_),
    .Y(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:756.8-760.4" *)
  NAND _355_ (
    .A(_020_),
    .B(_034_),
    .Y(_039_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:761.8-765.4" *)
  NAND _356_ (
    .A(_080_),
    .B(_039_),
    .Y(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:766.7-770.4" *)
  NOR _357_ (
    .A(_036_),
    .B(_040_),
    .Y(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:771.7-775.4" *)
  NOR _358_ (
    .A(_095_),
    .B(_030_),
    .Y(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:776.7-780.4" *)
  NOR _359_ (
    .A(rst),
    .B(_041_),
    .Y(_042_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:781.7-785.4" *)
  NOR _360_ (
    .A(_076_),
    .B(_039_),
    .Y(_043_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:786.8-790.4" *)
  NAND _361_ (
    .A(_021_),
    .B(_038_),
    .Y(_044_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:791.8-795.4" *)
  NAND _362_ (
    .A(_076_),
    .B(_039_),
    .Y(_045_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:796.8-800.4" *)
  NAND _363_ (
    .A(_042_),
    .B(_045_),
    .Y(_046_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:801.7-805.4" *)
  NOR _364_ (
    .A(_043_),
    .B(_046_),
    .Y(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:806.7-810.4" *)
  NOR _365_ (
    .A(_077_),
    .B(_043_),
    .Y(_047_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:811.8-815.4" *)
  NAND _366_ (
    .A(_042_),
    .B(_047_),
    .Y(_048_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:816.8-820.4" *)
  NAND _367_ (
    .A(_090_),
    .B(_035_),
    .Y(_049_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:821.7-825.4" *)
  NOR _368_ (
    .A(rst),
    .B(_049_),
    .Y(_050_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:826.7-829.4" *)
  NOT _369_ (
    .A(_050_),
    .Y(_051_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:830.8-834.4" *)
  NAND _370_ (
    .A(_048_),
    .B(_051_),
    .Y(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:835.7-839.4" *)
  NOR _371_ (
    .A(_077_),
    .B(_044_),
    .Y(_052_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:840.8-844.4" *)
  NAND _372_ (
    .A(_022_),
    .B(_043_),
    .Y(_053_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:845.7-849.4" *)
  NOR _373_ (
    .A(_078_),
    .B(_053_),
    .Y(_054_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:850.8-854.4" *)
  NAND _374_ (
    .A(_023_),
    .B(_052_),
    .Y(_055_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:855.8-859.4" *)
  NAND _375_ (
    .A(_078_),
    .B(_053_),
    .Y(_056_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:860.8-864.4" *)
  NAND _376_ (
    .A(_042_),
    .B(_056_),
    .Y(_057_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:865.7-869.4" *)
  NOR _377_ (
    .A(_054_),
    .B(_057_),
    .Y(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:870.7-874.4" *)
  NOR _378_ (
    .A(_079_),
    .B(_055_),
    .Y(_058_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:875.8-879.4" *)
  NAND _379_ (
    .A(_079_),
    .B(_055_),
    .Y(_059_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:880.8-884.4" *)
  NAND _380_ (
    .A(_042_),
    .B(_059_),
    .Y(_060_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:885.7-889.4" *)
  NOR _381_ (
    .A(_058_),
    .B(_060_),
    .Y(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:890.8-894.4" *)
  NAND _382_ (
    .A(_093_),
    .B(_117_),
    .Y(_061_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:895.8-899.4" *)
  NAND _383_ (
    .A(_135_),
    .B(_061_),
    .Y(_062_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:900.8-904.4" *)
  NAND _384_ (
    .A(_124_),
    .B(_062_),
    .Y(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:905.7-909.4" *)
  NOR _385_ (
    .A(_087_),
    .B(_032_),
    .Y(_063_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:910.8-914.4" *)
  NAND _386_ (
    .A(_094_),
    .B(_134_),
    .Y(_064_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:915.8-919.4" *)
  NAND _387_ (
    .A(_075_),
    .B(_064_),
    .Y(_065_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:920.7-924.4" *)
  NOR _388_ (
    .A(_063_),
    .B(_065_),
    .Y(_066_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:925.8-929.4" *)
  NAND _389_ (
    .A(_096_),
    .B(_066_),
    .Y(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:930.8-934.4" *)
  NAND _390_ (
    .A(_094_),
    .B(_032_),
    .Y(_067_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:935.8-939.4" *)
  NAND _391_ (
    .A(_135_),
    .B(_067_),
    .Y(_068_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:940.7-943.4" *)
  NOT _392_ (
    .A(_068_),
    .Y(_069_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:944.7-948.4" *)
  NOR _393_ (
    .A(_125_),
    .B(_069_),
    .Y(_070_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:949.8-953.4" *)
  NAND _394_ (
    .A(_026_),
    .B(_070_),
    .Y(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:954.8-958.4" *)
  NAND _395_ (
    .A(_122_),
    .B(_026_),
    .Y(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:959.8-963.4" *)
  NAND _396_ (
    .A(_084_),
    .B(_086_),
    .Y(_071_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:964.7-968.4" *)
  NOR _397_ (
    .A(_095_),
    .B(_071_),
    .Y(_072_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "APAC_synth.v:969.7-973.4" *)
  NOR _398_ (
    .A(_088_),
    .B(_072_),
    .Y(_136_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _402_ (
    .C(clk),
    .D(_012_),
    .Q(_148_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _403_ (
    .C(clk),
    .D(_013_),
    .Q(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _404_ (
    .C(clk),
    .D(_014_),
    .Q(_150_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _406_ (
    .C(clk),
    .D(_015_),
    .Q(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _407_ (
    .C(clk),
    .D(_016_),
    .Q(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _408_ (
    .C(clk),
    .D(_017_),
    .Q(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _409_ (
    .C(clk),
    .D(_018_),
    .Q(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _410_ (
    .C(clk),
    .D(_019_),
    .Q(_024_)
  );
  assign count0 = { _024_, _023_, _022_, _021_, _020_ };
  assign nxt_state[3:2] = { nxt_state[4], nxt_state[4] };
  assign state = { _150_, _150_, _150_, _149_, _148_ };
endmodule
