/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

(* top =  1  *)
(* src = "Automatic-Parking-Access-Control.v:13.1-142.10" *)
module ControladorParqueo(clk, rst, sensor_1, sensor_2, try_psswrd, psswrd_atmpt, alarm_1, alarm_2, open_gate, close_gate);
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  wire [4:0] _000_;
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  wire [4:0] _001_;
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  wire [4:0] _002_;
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  wire [4:0] _003_;
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  wire [4:0] _004_;
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  wire [4:0] _005_;
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  wire [4:0] _006_;
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  wire [4:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  (* src = "Automatic-Parking-Access-Control.v:35.11-35.17" *)
  wire _020_;
  (* src = "Automatic-Parking-Access-Control.v:35.11-35.17" *)
  wire _021_;
  (* src = "Automatic-Parking-Access-Control.v:35.11-35.17" *)
  wire _022_;
  (* src = "Automatic-Parking-Access-Control.v:35.11-35.17" *)
  wire _023_;
  (* src = "Automatic-Parking-Access-Control.v:35.11-35.17" *)
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:62.5-137.12|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire _120_;
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:62.5-137.12|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire _121_;
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:62.5-137.12|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _122_;
  (* src = "Automatic-Parking-Access-Control.v:28.13-28.25" *)
  wire _123_;
  (* src = "Automatic-Parking-Access-Control.v:28.13-28.25" *)
  wire _124_;
  (* src = "Automatic-Parking-Access-Control.v:28.13-28.25" *)
  wire _125_;
  (* src = "Automatic-Parking-Access-Control.v:28.13-28.25" *)
  wire _126_;
  (* src = "Automatic-Parking-Access-Control.v:28.13-28.25" *)
  wire _127_;
  (* src = "Automatic-Parking-Access-Control.v:28.13-28.25" *)
  wire _128_;
  (* src = "Automatic-Parking-Access-Control.v:28.13-28.25" *)
  wire _129_;
  (* src = "Automatic-Parking-Access-Control.v:28.13-28.25" *)
  wire _130_;
  (* src = "Automatic-Parking-Access-Control.v:27.12-27.15" *)
  wire _131_;
  (* src = "Automatic-Parking-Access-Control.v:27.17-27.25" *)
  wire _132_;
  (* src = "Automatic-Parking-Access-Control.v:27.27-27.35" *)
  wire _133_;
  (* src = "Automatic-Parking-Access-Control.v:34.11-34.16" *)
  wire _134_;
  (* src = "Automatic-Parking-Access-Control.v:34.11-34.16" *)
  wire _135_;
  (* src = "Automatic-Parking-Access-Control.v:34.11-34.16" *)
  wire _136_;
  (* src = "Automatic-Parking-Access-Control.v:27.37-27.47" *)
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire [1:0] _225_;
  wire _226_;
  wire [1:0] _227_;
  wire _228_;
  wire [1:0] _229_;
  wire _230_;
  wire [1:0] _231_;
  wire [1:0] _232_;
  wire [1:0] _233_;
  wire [1:0] _234_;
  wire _235_;
  wire [1:0] _236_;
  wire [1:0] _237_;
  wire [1:0] _238_;
  wire [1:0] _239_;
  wire [3:0] _240_;
  wire [1:0] _241_;
  wire [1:0] _242_;
  wire _243_;
  wire [1:0] _244_;
  wire _245_;
  wire [1:0] _246_;
  wire _247_;
  wire [4:0] _248_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:62.5-137.12|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [19:0] _249_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:62.5-137.12|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [19:0] _250_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:62.5-137.12|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [3:0] _251_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:62.5-137.12|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [4:0] _252_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:62.5-137.12|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [1:0] _253_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:62.5-137.12|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _254_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:102.38-102.46|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "4" *)
  wire [31:0] _255_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:102.38-102.46|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _256_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:102.38-102.46|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "5" *)
  wire [31:0] _257_;
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:62.5-137.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _258_;
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:62.5-137.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _259_;
  (* src = "Automatic-Parking-Access-Control.v:102.38-102.46|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _260_;
  (* src = "Automatic-Parking-Access-Control.v:31.12-31.19" *)
  output alarm_1;
  reg alarm_1;
  (* src = "Automatic-Parking-Access-Control.v:31.21-31.28" *)
  output alarm_2;
  reg alarm_2;
  (* src = "Automatic-Parking-Access-Control.v:27.7-27.10" *)
  input clk;
  wire clk;
  (* src = "Automatic-Parking-Access-Control.v:31.41-31.51" *)
  output close_gate;
  reg close_gate;
  (* src = "Automatic-Parking-Access-Control.v:35.11-35.17" *)
  wire [4:0] count0;
  (* src = "Automatic-Parking-Access-Control.v:37.11-37.20" *)
  wire [4:0] nxt_state;
  (* src = "Automatic-Parking-Access-Control.v:31.30-31.39" *)
  output open_gate;
  reg open_gate;
  (* src = "Automatic-Parking-Access-Control.v:28.13-28.25" *)
  input [7:0] psswrd_atmpt;
  wire [7:0] psswrd_atmpt;
  (* src = "Automatic-Parking-Access-Control.v:27.12-27.15" *)
  input rst;
  wire rst;
  (* src = "Automatic-Parking-Access-Control.v:27.17-27.25" *)
  input sensor_1;
  wire sensor_1;
  (* src = "Automatic-Parking-Access-Control.v:27.27-27.35" *)
  input sensor_2;
  wire sensor_2;
  (* src = "Automatic-Parking-Access-Control.v:34.11-34.16" *)
  wire [4:0] state;
  (* src = "Automatic-Parking-Access-Control.v:27.37-27.47" *)
  input try_psswrd;
  wire try_psswrd;
  NOT _261_ (
    .A(_024_),
    .Y(_059_)
  );
  NOT _262_ (
    .A(_022_),
    .Y(_060_)
  );
  NOT _263_ (
    .A(_020_),
    .Y(_061_)
  );
  NOT _264_ (
    .A(_136_),
    .Y(_062_)
  );
  NOT _265_ (
    .A(_135_),
    .Y(_063_)
  );
  NOT _266_ (
    .A(_137_),
    .Y(_064_)
  );
  NOT _267_ (
    .A(_129_),
    .Y(_065_)
  );
  NOT _268_ (
    .A(_132_),
    .Y(_066_)
  );
  NAND _269_ (
    .A(_021_),
    .B(_020_),
    .Y(_067_)
  );
  NOR _270_ (
    .A(_022_),
    .B(_137_),
    .Y(_068_)
  );
  NOR _271_ (
    .A(_024_),
    .B(_023_),
    .Y(_069_)
  );
  NAND _272_ (
    .A(_068_),
    .B(_069_),
    .Y(_070_)
  );
  NOR _273_ (
    .A(_067_),
    .B(_070_),
    .Y(_071_)
  );
  NOT _274_ (
    .A(_071_),
    .Y(_072_)
  );
  NAND _275_ (
    .A(_062_),
    .B(_134_),
    .Y(_073_)
  );
  NOT _276_ (
    .A(_073_),
    .Y(_074_)
  );
  NOR _277_ (
    .A(_136_),
    .B(_135_),
    .Y(_075_)
  );
  NAND _278_ (
    .A(_134_),
    .B(_075_),
    .Y(_076_)
  );
  NOT _279_ (
    .A(_076_),
    .Y(_121_)
  );
  NAND _280_ (
    .A(_125_),
    .B(_124_),
    .Y(_077_)
  );
  NAND _281_ (
    .A(_123_),
    .B(_065_),
    .Y(_078_)
  );
  NOR _282_ (
    .A(_077_),
    .B(_078_),
    .Y(_079_)
  );
  NAND _283_ (
    .A(_130_),
    .B(_128_),
    .Y(_080_)
  );
  NAND _284_ (
    .A(_127_),
    .B(_126_),
    .Y(_081_)
  );
  NOR _285_ (
    .A(_080_),
    .B(_081_),
    .Y(_082_)
  );
  NAND _286_ (
    .A(_079_),
    .B(_082_),
    .Y(_083_)
  );
  NOT _287_ (
    .A(_083_),
    .Y(_084_)
  );
  NAND _288_ (
    .A(_137_),
    .B(_084_),
    .Y(_085_)
  );
  NOT _289_ (
    .A(_085_),
    .Y(_086_)
  );
  NAND _290_ (
    .A(_121_),
    .B(_085_),
    .Y(_087_)
  );
  NOR _291_ (
    .A(_071_),
    .B(_087_),
    .Y(_088_)
  );
  NOR _292_ (
    .A(_136_),
    .B(_134_),
    .Y(_089_)
  );
  NOT _293_ (
    .A(_089_),
    .Y(_090_)
  );
  NOR _294_ (
    .A(_135_),
    .B(_090_),
    .Y(_091_)
  );
  NOR _295_ (
    .A(_133_),
    .B(_091_),
    .Y(_092_)
  );
  NAND _296_ (
    .A(_062_),
    .B(_135_),
    .Y(_093_)
  );
  NOR _297_ (
    .A(_134_),
    .B(_093_),
    .Y(_120_)
  );
  NAND _298_ (
    .A(_076_),
    .B(_090_),
    .Y(_094_)
  );
  NAND _299_ (
    .A(_132_),
    .B(_094_),
    .Y(_095_)
  );
  NOR _300_ (
    .A(_092_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _301_ (
    .A(_063_),
    .B(_073_),
    .Y(_097_)
  );
  NAND _302_ (
    .A(_135_),
    .B(_074_),
    .Y(_098_)
  );
  NOR _303_ (
    .A(_064_),
    .B(_098_),
    .Y(_099_)
  );
  NAND _304_ (
    .A(_137_),
    .B(_097_),
    .Y(_100_)
  );
  NOR _305_ (
    .A(_084_),
    .B(_100_),
    .Y(_101_)
  );
  NAND _306_ (
    .A(_083_),
    .B(_099_),
    .Y(_102_)
  );
  NOR _307_ (
    .A(_096_),
    .B(_101_),
    .Y(_103_)
  );
  NAND _308_ (
    .A(_132_),
    .B(_133_),
    .Y(_104_)
  );
  NOT _309_ (
    .A(_104_),
    .Y(_105_)
  );
  NOR _310_ (
    .A(_076_),
    .B(_105_),
    .Y(_106_)
  );
  NAND _311_ (
    .A(_121_),
    .B(_104_),
    .Y(_107_)
  );
  NOR _312_ (
    .A(_072_),
    .B(_107_),
    .Y(_108_)
  );
  NAND _313_ (
    .A(_064_),
    .B(_097_),
    .Y(_109_)
  );
  NOR _314_ (
    .A(_136_),
    .B(_108_),
    .Y(_110_)
  );
  NAND _315_ (
    .A(_109_),
    .B(_110_),
    .Y(_111_)
  );
  NAND _316_ (
    .A(_134_),
    .B(_111_),
    .Y(_112_)
  );
  NAND _317_ (
    .A(_103_),
    .B(_112_),
    .Y(_113_)
  );
  NOR _318_ (
    .A(_088_),
    .B(_113_),
    .Y(_114_)
  );
  NOR _319_ (
    .A(_131_),
    .B(_114_),
    .Y(_012_)
  );
  NAND _320_ (
    .A(_135_),
    .B(_111_),
    .Y(_115_)
  );
  NOR _321_ (
    .A(_076_),
    .B(_085_),
    .Y(_116_)
  );
  NAND _322_ (
    .A(_075_),
    .B(_105_),
    .Y(_117_)
  );
  NAND _323_ (
    .A(_066_),
    .B(_133_),
    .Y(_118_)
  );
  NAND _324_ (
    .A(_120_),
    .B(_118_),
    .Y(_119_)
  );
  NOT _325_ (
    .A(_119_),
    .Y(_025_)
  );
  NAND _326_ (
    .A(_102_),
    .B(_117_),
    .Y(_026_)
  );
  NOR _327_ (
    .A(_116_),
    .B(_025_),
    .Y(_027_)
  );
  NAND _328_ (
    .A(_115_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _329_ (
    .A(_026_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _330_ (
    .A(_131_),
    .B(_029_),
    .Y(_013_)
  );
  NOR _331_ (
    .A(_062_),
    .B(_131_),
    .Y(_014_)
  );
  NOR _332_ (
    .A(_085_),
    .B(_107_),
    .Y(_030_)
  );
  NOR _333_ (
    .A(_131_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _334_ (
    .A(_064_),
    .B(_107_),
    .Y(_032_)
  );
  NAND _335_ (
    .A(_137_),
    .B(_106_),
    .Y(_033_)
  );
  NOR _336_ (
    .A(_020_),
    .B(_032_),
    .Y(_034_)
  );
  NOR _337_ (
    .A(_061_),
    .B(_033_),
    .Y(_035_)
  );
  NAND _338_ (
    .A(_020_),
    .B(_032_),
    .Y(_036_)
  );
  NAND _339_ (
    .A(_031_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _340_ (
    .A(_034_),
    .B(_037_),
    .Y(_015_)
  );
  NOR _341_ (
    .A(_021_),
    .B(_035_),
    .Y(_038_)
  );
  NAND _342_ (
    .A(_021_),
    .B(_035_),
    .Y(_039_)
  );
  NAND _343_ (
    .A(_031_),
    .B(_039_),
    .Y(_040_)
  );
  NOR _344_ (
    .A(_038_),
    .B(_040_),
    .Y(_016_)
  );
  NOR _345_ (
    .A(_060_),
    .B(_039_),
    .Y(_041_)
  );
  NAND _346_ (
    .A(_060_),
    .B(_039_),
    .Y(_042_)
  );
  NAND _347_ (
    .A(_031_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _348_ (
    .A(_041_),
    .B(_043_),
    .Y(_017_)
  );
  NAND _349_ (
    .A(_023_),
    .B(_041_),
    .Y(_044_)
  );
  NOR _350_ (
    .A(_023_),
    .B(_041_),
    .Y(_045_)
  );
  NAND _351_ (
    .A(_031_),
    .B(_044_),
    .Y(_046_)
  );
  NOR _352_ (
    .A(_045_),
    .B(_046_),
    .Y(_018_)
  );
  NOR _353_ (
    .A(_059_),
    .B(_044_),
    .Y(_047_)
  );
  NAND _354_ (
    .A(_059_),
    .B(_044_),
    .Y(_048_)
  );
  NAND _355_ (
    .A(_031_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _356_ (
    .A(_047_),
    .B(_049_),
    .Y(_019_)
  );
  NOR _357_ (
    .A(_091_),
    .B(_108_),
    .Y(_008_)
  );
  NOR _358_ (
    .A(_086_),
    .B(_098_),
    .Y(_050_)
  );
  NAND _359_ (
    .A(_120_),
    .B(_104_),
    .Y(_051_)
  );
  NAND _360_ (
    .A(_062_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _361_ (
    .A(_050_),
    .B(_052_),
    .Y(_053_)
  );
  NAND _362_ (
    .A(_107_),
    .B(_053_),
    .Y(_009_)
  );
  NOR _363_ (
    .A(_076_),
    .B(_104_),
    .Y(_054_)
  );
  NAND _364_ (
    .A(_094_),
    .B(_119_),
    .Y(_055_)
  );
  NOR _365_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  NAND _366_ (
    .A(_087_),
    .B(_056_),
    .Y(_010_)
  );
  NAND _367_ (
    .A(_089_),
    .B(_119_),
    .Y(_011_)
  );
  NAND _368_ (
    .A(_093_),
    .B(_104_),
    .Y(_057_)
  );
  NOR _369_ (
    .A(_074_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _370_ (
    .A(_097_),
    .B(_058_),
    .Y(_122_)
  );
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  always @*
    if (!_159_) alarm_1 = _251_[2];
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  always @*
    if (!_168_) alarm_2 = _254_;
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  always @*
    if (!_181_) open_gate = _251_[2];
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _374_ (
    .C(clk),
    .D(_210_),
    .Q(state[0])
  );
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _375_ (
    .C(clk),
    .D(_212_),
    .Q(state[1])
  );
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _376_ (
    .C(clk),
    .D(_214_),
    .Q(state[3])
  );
  (* src = "Automatic-Parking-Access-Control.v:56.1-139.4" *)
  always @*
    if (!_182_) close_gate = _251_[1];
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _378_ (
    .C(clk),
    .D(_216_),
    .Q(count0[0])
  );
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _379_ (
    .C(clk),
    .D(_218_),
    .Q(count0[1])
  );
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _380_ (
    .C(clk),
    .D(_220_),
    .Q(count0[2])
  );
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _381_ (
    .C(clk),
    .D(_222_),
    .Q(count0[3])
  );
  (* src = "Automatic-Parking-Access-Control.v:43.1-51.4" *)
  DFF _382_ (
    .C(clk),
    .D(_224_),
    .Q(count0[4])
  );
  assign { _000_[4:2], _000_[0] } = 4'h0;
  assign { _001_[4:2], _001_[0] } = { 3'h0, _001_[1] };
  assign _004_[3:2] = { _004_[4], _004_[4] };
  assign _005_[3:2] = { _005_[4], _005_[4] };
  assign _006_[3:1] = { _006_[4], _006_[4], _006_[4] };
  assign _007_[3:1] = { _007_[4], _007_[4], _007_[4] };
  assign _225_[1] = state[3];
  assign _227_[1] = state[3];
  assign _231_[1] = _146_;
  assign _244_[1] = state[3];
  assign _246_[1] = state[3];
  assign { _248_[4:3], _248_[1:0] } = { _249_[16], _145_, _001_[1], _147_ };
  assign { _249_[19:17], _249_[13:12], _249_[9:7], _249_[5], _249_[3:2], _249_[0] } = { 3'h0, _249_[14], _249_[14], 3'h0, _249_[16], _249_[4], _249_[4], _249_[1] };
  assign { _250_[19:17], _250_[13:12], _250_[9:7], _250_[3:2], _250_[0] } = { 3'h0, _250_[14], _250_[14], 3'h0, _250_[4], _250_[4], _250_[1] };
  assign _252_[3:2] = { _252_[4], _252_[4] };
  assign _253_[0] = 1'h0;
  assign { _255_[31:5], _255_[0] } = { 27'h0000000, count0[0] };
  assign _256_[31:1] = { 27'h0000000, count0[4:1] };
  assign { _257_[31:5], _257_[0] } = { 26'h0000000, _255_[4], _256_[0] };
  assign { nxt_state[4], nxt_state[2] } = { nxt_state[3], nxt_state[3] };
  assign { state[4], state[2] } = { state[3], state[3] };
  assign _024_ = count0[4];
  assign _023_ = count0[3];
  assign _022_ = count0[2];
  assign _021_ = count0[1];
  assign _020_ = count0[0];
  assign _136_ = state[3];
  assign _135_ = state[1];
  assign _134_ = state[0];
  assign _131_ = rst;
  assign _210_ = _012_;
  assign _212_ = _013_;
  assign _214_ = _014_;
  assign _216_ = _015_;
  assign _218_ = _016_;
  assign _220_ = _017_;
  assign _222_ = _018_;
  assign _224_ = _019_;
  assign _130_ = psswrd_atmpt[7];
  assign _128_ = psswrd_atmpt[5];
  assign _127_ = psswrd_atmpt[4];
  assign _126_ = psswrd_atmpt[3];
  assign _125_ = psswrd_atmpt[2];
  assign _124_ = psswrd_atmpt[1];
  assign _123_ = psswrd_atmpt[0];
  assign _137_ = try_psswrd;
  assign _159_ = _008_;
  assign _168_ = _009_;
  assign _181_ = _010_;
  assign _251_[2] = _121_;
  assign _251_[1] = _120_;
  assign _182_ = _011_;
  assign _129_ = psswrd_atmpt[6];
  assign _132_ = sensor_1;
  assign _133_ = sensor_2;
  assign _254_ = _122_;
endmodule
