/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

(* cells_not_processed =  1  *)
(* src = "Automatic-Parking-Access-Control.v:13.1-168.10" *)
module ControladorParqueo(clk, rst, sensor_1, sensor_2, try_psswrd, psswrd_atmpt, alarm_1, alarm_2, open_gate, close_gate, nx_alarm_1, nx_alarm_2, nx_open_gate, nx_close_gate);
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire [4:0] _000_;
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire [4:0] _001_;
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire _002_;
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire _003_;
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire _004_;
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire _005_;
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire _006_;
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire [4:0] _007_;
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire [4:0] _008_;
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire [4:0] _009_;
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire _010_;
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire _011_;
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire [4:0] _012_;
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire [4:0] _013_;
  (* src = "Automatic-Parking-Access-Control.v:68.1-165.4" *)
  wire [4:0] _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire [3:0] _034_;
  wire [1:0] _035_;
  wire [1:0] _036_;
  wire _037_;
  wire [1:0] _038_;
  wire _039_;
  wire [1:0] _040_;
  wire [1:0] _041_;
  wire [1:0] _042_;
  wire _043_;
  wire [1:0] _044_;
  wire _045_;
  wire [1:0] _046_;
  wire [1:0] _047_;
  wire [1:0] _048_;
  wire [1:0] _049_;
  wire [1:0] _050_;
  wire _051_;
  wire _052_;
  wire [1:0] _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [19:0] _057_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [19:0] _058_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [3:0] _059_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [4:0] _060_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [2:0] _061_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [2:0] _062_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [2:0] _063_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire _064_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [1:0] _065_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [1:0] _066_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [2:0] _067_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [2:0] _068_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire _069_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [1:0] _070_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [1:0] _071_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:127.38-127.46|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "4" *)
  wire [31:0] _072_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:127.38-127.46|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _073_;
  (* force_downto = 32'd1 *)
  (* src = "Automatic-Parking-Access-Control.v:127.38-127.46|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "5" *)
  wire [31:0] _074_;
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _075_;
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _076_;
  (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _077_;
  (* src = "Automatic-Parking-Access-Control.v:127.38-127.46|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _078_;
  (* src = "Automatic-Parking-Access-Control.v:32.12-32.19" *)
  output alarm_1;
  reg alarm_1;
  (* src = "Automatic-Parking-Access-Control.v:32.21-32.28" *)
  output alarm_2;
  reg alarm_2;
  (* src = "Automatic-Parking-Access-Control.v:28.7-28.10" *)
  input clk;
  wire clk;
  (* src = "Automatic-Parking-Access-Control.v:32.41-32.51" *)
  output close_gate;
  reg close_gate;
  (* src = "Automatic-Parking-Access-Control.v:37.11-37.17" *)
  reg [4:0] count0;
  (* src = "Automatic-Parking-Access-Control.v:33.12-33.22" *)
  output nx_alarm_1;
  wire nx_alarm_1;
  (* src = "Automatic-Parking-Access-Control.v:33.24-33.34" *)
  output nx_alarm_2;
  wire nx_alarm_2;
  (* src = "Automatic-Parking-Access-Control.v:33.50-33.63" *)
  output nx_close_gate;
  wire nx_close_gate;
  (* src = "Automatic-Parking-Access-Control.v:33.36-33.48" *)
  output nx_open_gate;
  wire nx_open_gate;
  (* src = "Automatic-Parking-Access-Control.v:39.11-39.20" *)
  wire [4:0] nxt_state;
  (* src = "Automatic-Parking-Access-Control.v:32.30-32.39" *)
  output open_gate;
  reg open_gate;
  (* src = "Automatic-Parking-Access-Control.v:29.13-29.25" *)
  input [7:0] psswrd_atmpt;
  wire [7:0] psswrd_atmpt;
  (* src = "Automatic-Parking-Access-Control.v:28.12-28.15" *)
  input rst;
  wire rst;
  (* src = "Automatic-Parking-Access-Control.v:28.17-28.25" *)
  input sensor_1;
  wire sensor_1;
  (* src = "Automatic-Parking-Access-Control.v:28.27-28.35" *)
  input sensor_2;
  wire sensor_2;
  (* src = "Automatic-Parking-Access-Control.v:36.11-36.16" *)
  wire [4:0] state;
  (* src = "Automatic-Parking-Access-Control.v:28.37-28.47" *)
  input try_psswrd;
  wire try_psswrd;
  (* src = "Automatic-Parking-Access-Control.v:45.1-63.4" *)
  always @(posedge clk)
    if (rst) alarm_2 <= 1'h0;
    else alarm_2 <= nx_alarm_2;
  (* src = "Automatic-Parking-Access-Control.v:45.1-63.4" *)
  always @(posedge clk)
    if (rst) count0[0] <= 1'h0;
    else if (_018_) count0[0] <= _007_[0];
  (* src = "Automatic-Parking-Access-Control.v:45.1-63.4" *)
  always @(posedge clk)
    if (rst) count0[1] <= 1'h0;
    else if (_018_) count0[1] <= _007_[1];
  (* src = "Automatic-Parking-Access-Control.v:45.1-63.4" *)
  always @(posedge clk)
    if (rst) count0[2] <= 1'h0;
    else if (_018_) count0[2] <= _007_[2];
  (* src = "Automatic-Parking-Access-Control.v:45.1-63.4" *)
  always @(posedge clk)
    if (rst) count0[3] <= 1'h0;
    else if (_018_) count0[3] <= _007_[3];
  (* src = "Automatic-Parking-Access-Control.v:45.1-63.4" *)
  always @(posedge clk)
    if (rst) count0[4] <= 1'h0;
    else if (_018_) count0[4] <= _007_[4];
  reg \state_reg[0] ;
  (* src = "Automatic-Parking-Access-Control.v:45.1-63.4" *)
  always @(posedge clk)
    if (rst) \state_reg[0]  <= 1'h0;
    else if (_019_) \state_reg[0]  <= nxt_state[0];
  assign state[0] = \state_reg[0] ;
  reg \state_reg[1] ;
  (* src = "Automatic-Parking-Access-Control.v:45.1-63.4" *)
  always @(posedge clk)
    if (rst) \state_reg[1]  <= 1'h0;
    else if (_019_) \state_reg[1]  <= nxt_state[1];
  assign state[1] = \state_reg[1] ;
  reg \state_reg[3] ;
  (* src = "Automatic-Parking-Access-Control.v:45.1-63.4" *)
  always @(posedge clk)
    if (rst) \state_reg[3]  <= 1'h0;
    else if (_019_) \state_reg[3]  <= nxt_state[3];
  assign state[3] = \state_reg[3] ;
  (* src = "Automatic-Parking-Access-Control.v:45.1-63.4" *)
  always @(posedge clk)
    if (rst) alarm_1 <= 1'h0;
    else alarm_1 <= nx_alarm_1;
  (* src = "Automatic-Parking-Access-Control.v:45.1-63.4" *)
  always @(posedge clk)
    if (rst) open_gate <= 1'h0;
    else open_gate <= nx_open_gate;
  (* src = "Automatic-Parking-Access-Control.v:45.1-63.4" *)
  always @(posedge clk)
    if (rst) close_gate <= 1'h0;
    else close_gate <= nx_close_gate;
  assign _021_ = ~psswrd_atmpt[0];
  assign _022_ = ~psswrd_atmpt[1];
  assign _023_ = ~psswrd_atmpt[2];
  assign _024_ = ~psswrd_atmpt[3];
  assign _025_ = ~psswrd_atmpt[4];
  assign _026_ = ~psswrd_atmpt[5];
  assign _027_ = ~psswrd_atmpt[7];
  assign _028_ = ~count0[1];
  assign _073_[0] = ~count0[0];
  assign _030_ = ~state[0];
  assign _029_ = ~state[1];
  assign _036_[0] = _073_[0] |(* src = "Automatic-Parking-Access-Control.v:131.30-131.45" *)  _028_;
  assign _036_[1] = count0[2] |(* src = "Automatic-Parking-Access-Control.v:131.30-131.45" *)  count0[3];
  assign _037_ = _036_[0] |(* src = "Automatic-Parking-Access-Control.v:131.30-131.45" *)  _036_[1];
  assign _032_ = _037_ |(* src = "Automatic-Parking-Access-Control.v:131.30-131.45" *)  count0[4];
  assign _034_[0] = _021_ |(* src = "Automatic-Parking-Access-Control.v:156.27-156.49" *)  _022_;
  assign _034_[1] = _023_ |(* src = "Automatic-Parking-Access-Control.v:156.27-156.49" *)  _024_;
  assign _034_[2] = _025_ |(* src = "Automatic-Parking-Access-Control.v:156.27-156.49" *)  _026_;
  assign _034_[3] = psswrd_atmpt[6] |(* src = "Automatic-Parking-Access-Control.v:156.27-156.49" *)  _027_;
  assign _035_[0] = _034_[0] |(* src = "Automatic-Parking-Access-Control.v:156.27-156.49" *)  _034_[1];
  assign _035_[1] = _034_[2] |(* src = "Automatic-Parking-Access-Control.v:156.27-156.49" *)  _034_[3];
  assign _001_[1] = _035_[0] |(* src = "Automatic-Parking-Access-Control.v:156.27-156.49" *)  _035_[1];
  assign _038_[0] = _030_ |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *)  _029_;
  assign _039_ = _038_[0] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *)  state[3];
  assign _031_ = _039_ |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *)  state[3];
  assign _040_[1] = _016_ & _015_;
  assign _019_ = _017_ & _040_[1];
  assign _041_[0] = _059_[0] | _059_[2];
  assign _041_[1] = _059_[3] | _059_[1];
  assign _017_ = _041_[0] | _041_[1];
  assign _042_[0] = state[0] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *)  _029_;
  assign _043_ = _042_[0] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *)  state[3];
  assign _056_ = _043_ |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *)  state[3];
  assign _044_[0] = _030_ |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *)  state[1];
  assign _045_ = _044_[0] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *)  state[3];
  assign _033_ = _045_ |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *)  state[3];
  assign _016_ = try_psswrd | _031_;
  assign _046_[0] = try_psswrd | _057_[16];
  assign _046_[1] = _032_ | _033_;
  assign _015_ = _046_[0] | _046_[1];
  assign _047_[0] = try_psswrd & _059_[2];
  assign _018_ = _047_[0] & _020_;
  assign _060_[4] = _058_[4] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _058_[14];
  assign _048_[0] = _058_[1] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _058_[6];
  assign _048_[1] = _058_[11] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _058_[16];
  assign _060_[1] = _048_[0] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _048_[1];
  assign _049_[0] = _058_[1] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _058_[5];
  assign _049_[1] = _058_[10] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _058_[15];
  assign _060_[0] = _049_[0] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _049_[1];
  assign _050_[0] = _059_[0] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _059_[1];
  assign _050_[1] = _059_[2] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _059_[3];
  assign _075_ = _050_[0] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _050_[1];
  assign _051_ = _062_[0] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _062_[1];
  assign _064_ = _051_ |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _058_[16];
  assign _052_ = _059_[0] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _063_[1];
  assign _076_ = _052_ |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _059_[3];
  assign _069_ = _068_[0] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _068_[1];
  assign _063_[1] = _059_[1] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _059_[2];
  assign _077_ = _063_[1] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _059_[3];
  assign _053_[0] = state[0] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *)  state[1];
  assign _054_ = _053_[0] |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *)  state[3];
  assign _055_ = _054_ |(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *)  state[3];
  assign _059_[0] = ~(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *) _031_;
  assign _059_[1] = ~(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *) _056_;
  assign _059_[3] = ~(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *) _055_;
  assign _059_[2] = ~(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12" *) _033_;
  assign _057_[16] = sensor_1 &(* src = "Automatic-Parking-Access-Control.v:138.25-138.45" *)  sensor_2;
  assign _010_ = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:156.27-156.49|Automatic-Parking-Access-Control.v:156.23-159.52" *) alarm_2 : 1'h0;
  assign _057_[1] = try_psswrd ? (* src = "Automatic-Parking-Access-Control.v:154.25-154.35|Automatic-Parking-Access-Control.v:154.21-160.24" *) _001_[1] : 1'hx;
  assign _057_[4] = try_psswrd ? (* src = "Automatic-Parking-Access-Control.v:154.25-154.35|Automatic-Parking-Access-Control.v:154.21-160.24" *) 1'h0 : 1'hx;
  assign _061_[0] = try_psswrd ? (* src = "Automatic-Parking-Access-Control.v:154.25-154.35|Automatic-Parking-Access-Control.v:154.21-160.24" *) _010_ : alarm_2;
  assign _000_[1] = ~(* src = "Automatic-Parking-Access-Control.v:144.30-144.38|Automatic-Parking-Access-Control.v:144.26-148.50" *) sensor_2;
  assign _003_ = sensor_2 ? (* src = "Automatic-Parking-Access-Control.v:144.30-144.38|Automatic-Parking-Access-Control.v:144.26-148.50" *) 1'h1 : close_gate;
  assign _011_ = sensor_2 ? (* src = "Automatic-Parking-Access-Control.v:144.30-144.38|Automatic-Parking-Access-Control.v:144.26-148.50" *) 1'h0 : open_gate;
  assign _057_[6] = _057_[16] ? (* src = "Automatic-Parking-Access-Control.v:138.25-138.45|Automatic-Parking-Access-Control.v:138.21-148.50" *) 1'h1 : _000_[1];
  assign _070_[0] = _057_[16] ? (* src = "Automatic-Parking-Access-Control.v:138.25-138.45|Automatic-Parking-Access-Control.v:138.21-148.50" *) close_gate : _003_;
  assign _067_[0] = _057_[16] ? (* src = "Automatic-Parking-Access-Control.v:138.25-138.45|Automatic-Parking-Access-Control.v:138.21-148.50" *) open_gate : _011_;
  assign _005_ = _032_ ? (* src = "Automatic-Parking-Access-Control.v:131.30-131.45|Automatic-Parking-Access-Control.v:131.26-132.46" *) alarm_1 : 1'h1;
  assign _014_[0] = _032_ ? (* src = "Automatic-Parking-Access-Control.v:131.30-131.45|Automatic-Parking-Access-Control.v:131.26-132.46" *) 1'h1 : 1'hx;
  assign _014_[4] = _032_ ? (* src = "Automatic-Parking-Access-Control.v:131.30-131.45|Automatic-Parking-Access-Control.v:131.26-132.46" *) 1'h0 : 1'hx;
  assign _013_[0] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:126.27-126.49|Automatic-Parking-Access-Control.v:126.23-129.26" *) 1'h1 : 1'hx;
  assign _013_[4] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:126.27-126.49|Automatic-Parking-Access-Control.v:126.23-129.26" *) 1'h0 : 1'hx;
  assign _008_[0] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:126.27-126.49|Automatic-Parking-Access-Control.v:126.23-129.26" *) _073_[0] : 1'hx;
  assign _008_[1] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:126.27-126.49|Automatic-Parking-Access-Control.v:126.23-129.26" *) _074_[1] : 1'hx;
  assign _008_[2] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:126.27-126.49|Automatic-Parking-Access-Control.v:126.23-129.26" *) _074_[2] : 1'hx;
  assign _008_[3] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:126.27-126.49|Automatic-Parking-Access-Control.v:126.23-129.26" *) _074_[3] : 1'hx;
  assign _008_[4] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:126.27-126.49|Automatic-Parking-Access-Control.v:126.23-129.26" *) _074_[4] : 1'hx;
  assign _012_[0] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:119.27-119.49|Automatic-Parking-Access-Control.v:119.23-129.26" *) _013_[0] : 1'h0;
  assign _012_[1] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:119.27-119.49|Automatic-Parking-Access-Control.v:119.23-129.26" *) _013_[4] : 1'h1;
  assign _012_[4] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:119.27-119.49|Automatic-Parking-Access-Control.v:119.23-129.26" *) _013_[4] : 1'h0;
  assign _007_[0] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:119.27-119.49|Automatic-Parking-Access-Control.v:119.23-129.26" *) _008_[0] : 1'h0;
  assign _007_[1] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:119.27-119.49|Automatic-Parking-Access-Control.v:119.23-129.26" *) _008_[1] : 1'h0;
  assign _007_[2] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:119.27-119.49|Automatic-Parking-Access-Control.v:119.23-129.26" *) _008_[2] : 1'h0;
  assign _007_[3] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:119.27-119.49|Automatic-Parking-Access-Control.v:119.23-129.26" *) _008_[3] : 1'h0;
  assign _007_[4] = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:119.27-119.49|Automatic-Parking-Access-Control.v:119.23-129.26" *) _008_[4] : 1'h0;
  assign _006_ = _001_[1] ? (* src = "Automatic-Parking-Access-Control.v:119.27-119.49|Automatic-Parking-Access-Control.v:119.23-129.26" *) open_gate : 1'h1;
  assign _009_[0] = try_psswrd ? (* src = "Automatic-Parking-Access-Control.v:117.30-117.40|Automatic-Parking-Access-Control.v:117.26-132.46" *) _012_[0] : _014_[0];
  assign _009_[1] = try_psswrd ? (* src = "Automatic-Parking-Access-Control.v:117.30-117.40|Automatic-Parking-Access-Control.v:117.26-132.46" *) _012_[1] : _014_[4];
  assign _009_[4] = try_psswrd ? (* src = "Automatic-Parking-Access-Control.v:117.30-117.40|Automatic-Parking-Access-Control.v:117.26-132.46" *) _012_[4] : _014_[4];
  assign _004_ = try_psswrd ? (* src = "Automatic-Parking-Access-Control.v:117.30-117.40|Automatic-Parking-Access-Control.v:117.26-132.46" *) _006_ : open_gate;
  assign _002_ = try_psswrd ? (* src = "Automatic-Parking-Access-Control.v:117.30-117.40|Automatic-Parking-Access-Control.v:117.26-132.46" *) alarm_1 : _005_;
  assign _061_[1] = _057_[16] ? (* src = "Automatic-Parking-Access-Control.v:111.25-111.45|Automatic-Parking-Access-Control.v:111.21-132.46" *) 1'h1 : alarm_2;
  assign _057_[10] = _057_[16] ? (* src = "Automatic-Parking-Access-Control.v:111.25-111.45|Automatic-Parking-Access-Control.v:111.21-132.46" *) 1'h1 : _009_[0];
  assign _057_[11] = _057_[16] ? (* src = "Automatic-Parking-Access-Control.v:111.25-111.45|Automatic-Parking-Access-Control.v:111.21-132.46" *) 1'h1 : _009_[1];
  assign _057_[14] = _057_[16] ? (* src = "Automatic-Parking-Access-Control.v:111.25-111.45|Automatic-Parking-Access-Control.v:111.21-132.46" *) 1'h0 : _009_[4];
  assign _067_[1] = _057_[16] ? (* src = "Automatic-Parking-Access-Control.v:111.25-111.45|Automatic-Parking-Access-Control.v:111.21-132.46" *) open_gate : _004_;
  assign _065_[0] = _057_[16] ? (* src = "Automatic-Parking-Access-Control.v:111.25-111.45|Automatic-Parking-Access-Control.v:111.21-132.46" *) alarm_1 : _002_;
  assign _057_[15] = _057_[16] ? (* src = "Automatic-Parking-Access-Control.v:99.25-99.45|Automatic-Parking-Access-Control.v:99.21-106.46" *) 1'h1 : sensor_1;
  assign nxt_state[0] = _075_ ? (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _060_[0] : 1'hx;
  assign nxt_state[1] = _075_ ? (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _060_[1] : 1'hx;
  assign nxt_state[3] = _075_ ? (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _060_[4] : 1'hx;
  assign nx_alarm_2 = _076_ ? (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _064_ : alarm_2;
  assign nx_alarm_1 = _050_[1] ? (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _066_[0] : alarm_1;
  assign nx_open_gate = _077_ ? (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _069_ : open_gate;
  assign nx_close_gate = _041_[1] ? (* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _071_[0] : close_gate;
  assign _020_ = ~_057_[16];
  assign _072_[3] = _078_ &(* src = "Automatic-Parking-Access-Control.v:127.38-127.46|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _072_[1];
  assign _072_[1] = count0[1] &(* src = "Automatic-Parking-Access-Control.v:127.38-127.46|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  count0[0];
  assign _078_ = count0[3] &(* src = "Automatic-Parking-Access-Control.v:127.38-127.46|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  count0[2];
  assign _072_[2] = count0[2] &(* src = "Automatic-Parking-Access-Control.v:127.38-127.46|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _072_[1];
  assign _058_[15] = _057_[15] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _059_[3];
  assign _058_[16] = _057_[16] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _059_[3];
  assign _058_[10] = _057_[10] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _059_[2];
  assign _058_[11] = _057_[11] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _059_[2];
  assign _058_[14] = _057_[14] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _059_[2];
  assign _058_[5] = _057_[16] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _059_[1];
  assign _058_[6] = _057_[6] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _059_[1];
  assign _058_[1] = _057_[1] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _059_[0];
  assign _058_[4] = _057_[4] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _059_[0];
  assign _062_[1] = _061_[1] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _063_[1];
  assign _062_[0] = _061_[0] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _059_[0];
  assign _066_[0] = _065_[0] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _059_[2];
  assign _068_[1] = _067_[1] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _059_[2];
  assign _068_[0] = _067_[0] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _059_[1];
  assign _071_[0] = _070_[0] &(* src = "Automatic-Parking-Access-Control.v:0.0-0.0|Automatic-Parking-Access-Control.v:85.5-163.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _059_[1];
  assign _074_[1] = count0[1] ^(* src = "Automatic-Parking-Access-Control.v:127.38-127.46|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  count0[0];
  assign _074_[2] = count0[2] ^(* src = "Automatic-Parking-Access-Control.v:127.38-127.46|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _072_[1];
  assign _074_[3] = count0[3] ^(* src = "Automatic-Parking-Access-Control.v:127.38-127.46|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _072_[2];
  assign _074_[4] = count0[4] ^(* src = "Automatic-Parking-Access-Control.v:127.38-127.46|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _072_[3];
  assign { _000_[4:2], _000_[0] } = 4'h0;
  assign { _001_[4:2], _001_[0] } = { 3'h0, _001_[1] };
  assign _009_[3:2] = { _009_[4], _009_[4] };
  assign _012_[3:2] = { _012_[4], _012_[4] };
  assign _013_[3:1] = { _013_[4], _013_[4], _013_[4] };
  assign _014_[3:1] = { _014_[4], _014_[4], _014_[4] };
  assign _038_[1] = state[3];
  assign _040_[0] = _017_;
  assign _042_[1] = state[3];
  assign _044_[1] = state[3];
  assign _047_[1] = _020_;
  assign _053_[1] = state[3];
  assign { _057_[19:17], _057_[13:12], _057_[9:7], _057_[5], _057_[3:2], _057_[0] } = { 3'h0, _057_[14], _057_[14], 3'h0, _057_[16], _057_[4], _057_[4], _057_[1] };
  assign { _058_[19:17], _058_[13:12], _058_[9:7], _058_[3:2], _058_[0] } = { 3'h0, _058_[14], _058_[14], 3'h0, _058_[4], _058_[4], _058_[1] };
  assign _060_[3:2] = { _060_[4], _060_[4] };
  assign _061_[2] = _057_[16];
  assign _062_[2] = _058_[16];
  assign { _063_[2], _063_[0] } = { _059_[3], _059_[0] };
  assign _065_[1] = 1'h0;
  assign _066_[1] = 1'h0;
  assign _067_[2] = 1'h0;
  assign _068_[2] = 1'h0;
  assign _070_[1] = 1'h0;
  assign _071_[1] = 1'h0;
  assign { _072_[31:5], _072_[0] } = { 27'h0000000, count0[0] };
  assign _073_[31:1] = { 27'h0000000, count0[4:1] };
  assign { _074_[31:5], _074_[0] } = { 26'h0000000, _072_[4], _073_[0] };
  assign { nxt_state[4], nxt_state[2] } = { nxt_state[3], nxt_state[3] };
  assign { state[4], state[2] } = { state[3], state[3] };
endmodule
